@MASTER_KEY = {{$processEnv MASTER_KEY}}


POST http://localhost:3000/api/users 
content-type: application/json

{
    "email":"perlinson_2008@163.com",
    "password":"123456",
}


###
POST http://localhost:64414/api/auth
content-type: application/json

{
    "email":"perlinson_2008@163.com",
    "password":"123456",
}


###
curl -X POST http://0.0.0.0:64414/api/users -i -d "email=perlinson_2008@163.com&password=123456&access_token=m86byI6X4045jmQBsuqYM4mk7sSRVg5q"
